version: "3"
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
      - "8080:8080"
    extra_hosts:
    - "host.docker.internal:host-gateway"