# Use the official Python image as a parent image
FROM python:3.9-slim

ENV PORT="8999"

# Set the working directory inside the container
WORKDIR /app

# Copy the requirements.txt file into the container
COPY requirements.txt .

# Install the required Python packages
RUN pip install -r requirements.txt

# Copy the entire application directory into the container
COPY main.py .

RUN mkdir -p scheduler/scheduler_result

# Expose the port that the FastAPI application will run on
EXPOSE 8000

# Command to run the FastAPI application using Uvicorn
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
