list_of_station_1to17 = [
    "01 FLOOR & LINO ASSEMBLY",
    "02 BUILDING STAGE 1",
    "03 BUILDING STAGE 2",
    "04 ELECTRICAL 12V",
    "05 ELECTRICAL 240V",
    "06 WALLS ASSEMBLY",
    "07 ROOF ASSEMBLY",
    "08 J-MOULD / SPLASHBACK",
    "09 QUALITY CONTROL STATION 1",
    "10 ELECTRICAL FIT OFF",
    "11 FINISHING STAGE 1",
    "12 FINISHING STAGE 2",
    "13 QUALITY CONTROL STATION 2",
    "14 DOORS & DRAWS",
    "15 GREEN TAG / ELECTRICAL TESTING",
    "16 QUALITY CONTROL/ FINAL DETAIL",
    "17 FINAL DETAIL"
]
