name: Node.js CI

# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:

    # This job runs on a Linux machine.
    runs-on: ubuntu-latest

    # Define a strategy for running the job with multiple versions of Node.js.
    strategy:
      matrix:
        node-version: [14, 16, 18] # Define Node.js versions here.

    # Steps represent a sequence of tasks to be performed.
    steps:
    - name: Checkout Repository
      # This step checks out your repository under $GITHUB_WORKSPACE, so the job can access it.
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      # This step sets up a Node.js environment with the version from the matrix.
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      # Change the working directory to the frontend directory where your Node.js app is located.
      working-directory: ./frontend
      # Install dependencies from your project's package.json file.
      run: npm install

    - name: Build React App
      # Build your Node.js application.
      working-directory: ./frontend
      run: npm run build

    # Add additional steps as needed (e.g., for caching, testing, deployment, etc.)
